### ISSUE TITLE
Error when launching the app

### ISSUE THREAD

**Issue by pierrederuel** [FranPitri/flutter_redux_boilerplate#3]
Thanks for this repo, it's really useful!

Since I have updated my version of flutter and got this error:

type 'List<dynamic>' is not a subtype of type 'List<(Store<AppState>, dynamic, (dynamic) => void) => void>' where
  List is from dart:core
#0      createStore (package:flutter_redux_boilerplate/store/store.dart:11:21)

I tried to to change the type but no success, could you take a look?

Here's my version of Flutter:

Flutter 0.2.8 • channel beta • https://github.com/flutter/flutter.git
Framework • revision b397406561 (8 days ago) • 2018-04-02 13:53:20 -0700
Engine • revision c903c217a1
Tools • Dart 2.0.0-dev.43.0.flutter-52afcba357

**Comment by pitriq** [comment]
Hey there! Glad to hear it's being helpful!

Please check the latest changes in `develop` branch. I've updated most of this repo's dependencies. Since most of them were updated in order to support Dart 2, I had to do a bit of refactoring.

Give it a try and tell me how it went.

**Comment by pierrederuel** [comment]
Thanks a lot! Everything is ok except the login form:
When I type into the form field nothing appears in the text field.

**Comment by pitriq** [comment]
No problem! Hmm, are you running it on an Android or an iOS device? 

@hjlxy commented in #4 that there were some UI issues when running this on iOS simulator. I have neither a Mac nor an iPhone so I could not really test this. Would you mind sending a PR in case you mange to fix it?

Since the original issue is solved, I'm closing this one and merging `develop` into `master`. Feel free to fill a new one if something else shows up!
